version: '3.9'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootik
      MYSQL_DATABASE: hhpr
      MYSQL_USER: hhpr
      MYSQL_PASSWORD: hhprpw